default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5

codio : &codio
    host: localhost

development:
    <<: *codio
    <<: *default
    database: skillsesh_signup_development

test:
    <<: *codio
    <<: *default
    database: skillsesh_signup_test

production:
    <<: *default
