default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5

development:
    host: localhost
    <<: *default
    database: skillsesh_signup_development

test:
    host: localhost
    <<: *default
    database: skillsesh_signup_test

production:
    <<: *default
