facebook_id: '666569030069782'
facebook_secret: '5b03687fa93a6ea5c54f6a33d781af18'

google_id: '286227017715-q6p8o4j3aj70j1cp4rpri0gprk4rjsjp.apps.googleusercontent.com'
google_secret: 'pFzz4RvqjPkvizV7Ay9O8UD1 '

linkedin_id: '75rdk837koxmln'
linkedin_secret: 'eACuYWhPicqxN8bO'

mailchimp_key: 'aa9be7b96ec19a9ee1c60f453318e887-us3'

aws_id: 'AKIAI3JTWE44EI22UUCQ'
aws_secret: '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'

default: &default
  secret_key_base: 012345678901234567890

development:
  <<: *default

test:
  <<: *default
